# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6827b86c46e4454c469387d6b85084820d4c681336f6ef539bab613210ac60ed7cbab03c309c2f844394e72bcf764f0cbe02dbf3d13e22006003b50d94397463

test:
  secret_key_base: fdda3e451fe6c7eb7a2df6b35eaa5a6b6ac875f97e7db2aa75573cec438304c7539b65884da0190cfeb6017b5b46a213253c05aa7a3be9d585098818be3494d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
